import * as cheerio from 'cheerio';

/**
 * Timestamp patterns to remove from HTML content
 */
const TIMESTAMP_PATTERNS = [
  /\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/g,  // ISO 8601
  /\d{1,2}\/\d{1,2}\/\d{2,4}/g,             // US date (MM/DD/YYYY)
  /\d{1,2}:\d{2}(:\d{2})?\s*(AM|PM|am|pm)?/g, // Time patterns
  /\b\d{10,13}\b/g,                          // Unix timestamps
  /Updated:?\s*\d+\s*(second|minute|hour|day)s?\s*ago/gi, // Relative time
];

/**
 * Dynamic attribute patterns used by frameworks (Vue, React, Angular)
 */
const DYNAMIC_ATTR_PATTERNS = [
  /^data-v-/,        // Vue scoped styles
  /^ng-/,            // Angular
  /-[a-f0-9]{6,}$/i, // Hash suffixes (e.g., component-abc123def)
];

/**
 * Checks if an attribute value matches a dynamic pattern
 */
function isDynamicAttribute(value: string): boolean {
  return DYNAMIC_ATTR_PATTERNS.some(pattern => pattern.test(value));
}

/**
 * Normalizes HTML content to reduce false positives in change detection.
 *
 * This function:
 * - Removes script and noscript tags
 * - Removes style tags and stylesheet links
 * - Removes HTML comments
 * - Removes CSRF tokens and tracking elements
 * - Removes dynamic IDs generated by frameworks
 * - Removes timestamp patterns
 * - Normalizes whitespace
 *
 * @param html - The raw HTML content to normalize
 * @returns Normalized HTML string
 */
export function normalizeHtml(html: string): string {
  const $ = cheerio.load(html);

  // Remove script tags and content
  $('script').remove();
  $('noscript').remove();

  // Remove style tags and stylesheet links
  $('style').remove();
  $('link[rel="stylesheet"]').remove();

  // Remove HTML comments
  $('*').contents().filter(function() {
    return this.type === 'comment';
  }).remove();

  // Remove common dynamic/tracking elements
  $('meta[name="csrf-token"]').remove();
  $('input[name="_token"]').remove();
  $('[data-analytics]').removeAttr('data-analytics');
  $('[data-tracking]').removeAttr('data-tracking');

  // Remove dynamic IDs
  $('[id]').each(function() {
    const id = $(this).attr('id');
    if (id && isDynamicAttribute(id)) {
      $(this).removeAttr('id');
    }
  });

  // Get HTML string
  let normalized = $.html();

  // Remove timestamp patterns
  for (const pattern of TIMESTAMP_PATTERNS) {
    normalized = normalized.replace(pattern, '');
  }

  // Normalize whitespace
  return normalized
    .replace(/>\s+</g, '><')   // Remove whitespace between tags
    .replace(/\s+/g, ' ')       // Collapse multiple spaces
    .trim();                    // Remove leading/trailing whitespace
}
